config/routes.rb
Rails.application.routes.draw do  
  devise_for :employers, :controllers => {:registrations => "employers/registrations"}
  devise_for :users
  resources :jobs do
   resources :job_applications, :shallow=>true
    collection do
      get 'my_index'
      get 'all_index'
      get 'top_job'
      get 'user_show_view'
      scope ":id" do
        get 'applicants'
      end
    end
  end
  resources :resume_documents do
    collection do
      get 'employer_show_view'
    end
  end
  root "home#index"

end

app/models/job.rb
class Job < ActiveRecord::Base
  mount_uploader :attachment, JobAttachmentUploader
  validates :filename, presence: true
  validates :position, presence: true
  belongs_to :employer
  has_many :job_applications, dependent: :destroy
  accepts_nested_attributes_for :job_applications
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :set_job, only: [ :show, :user_show_view, :edit, :update, :destroy, :applicants]

  def all_index
    @employers = Employer.all
    @jobs = Job.all
  end

  def show
    if user_signed_in?
      redirect_to user_show_view_jobs_path(:id=>@job.id)
    end
    @employer=Employer.find(@job.employer_id)
    @job_data=JSON.parse(IO.read("#{Rails.root}/#{@job.datafile}"))
  end
  
  def user_show_view
    @employer=Employer.find(@job.employer_id)
    @applied=false
    @job_data=JSON.parse(IO.read("#{Rails.root}/#{@job.datafile}"))
    @user=User.find(current_user)
    @apple=false
    if @user.resume_document.filename
      @applications=@user.job_applications.map{|job_application| job_application.job}
      @applications.each do |app|
        if app.id==@job.id
          @applied=true
        end
      end
      @job_application=@user.job_applications.new
      @apple=true
      @resume_data=JSON.parse(IO.read("#{Rails.root}/#{@user.resume_document.datafile}"))
      @matching_data=matching(@job_data, @resume_data)
      @result_hash=compare(@matching_data)
    end
  end

  def top_job
      @tophash=Hash.new()
      @industry_hash=Hash.new()
      @user=User.find(current_user)
      @resume_data=JSON.parse(IO.read("#{Rails.root}/#{@user.resume_document.datafile}"))
      @jobs=Job.all
      @jobs.each do |job|
        if @job_data=JSON.parse(IO.read("#{Rails.root}/#{job.datafile}"))
          @matching_data=matching(@job_data, @resume_data)
          @result_hash=compare(@matching_data)
          if @industry_hash[@job_data["industry"]["position"]]          
            @industry_hash[@job_data["industry"]["position"]]=((@industry_hash[@job_data["industry"]["position"]]+ @result_hash["total"])/2)
          else
            @industry_hash[@job_data["industry"]["position"]]=@result_hash["total"]
          end
          @tophash[@jobs.index(job)]=[@result_hash["total"], job]
        end
      end
      @tophash=@tophash.sort_by {|key, value| value[0]}.reverse
      @tophash=@tophash[0,5]
      @industry_hash=@industry_hash.sort_by{|key, value| value}.reverse
      @industry_hash=@industry_hash[0,5]
  end

  def my_index
    if employer_signed_in?
      @jobs=Job.joins(:employer).where(:employer_id => params[:id])
    else
      @applications=current_user.job_applications.map{|job_app| job_app.job}
      @jobs=Job.all
    end
  end

  def applicants
    @tophash=Hash.new()
    @job_data=JSON.parse(IO.read("#{Rails.root}/#{@job.datafile}"))
    @users=User.all
    @users.each do |user|
      if !@job.job_applications.exists?(:user_id=>user.id)
        if @resume_data=JSON.parse(IO.read("#{Rails.root}/#{user.resume_document.datafile}"))
          @matching_data=matching(@job_data, @resume_data)
          @result_hash=compare(@matching_data)
          @tophash[@users.index(user)]=[user, @result_hash["total"]]
        end
      end
    end
    @tophash=@tophash.sort_by {|key, value| value[0]}.reverse
    @tophash=@tophash[0,10]

  end

  def new
    @job=Job.new
    @job.job_applications.new
  end

  def create
    if params[:job][:attachment].blank?
      redirect_to new_job_path, notice: 'Job listing file cannot be blank.'
    else
      @job=Job.new(job_params)
      @job.filename=File.basename(@job.attachment_url)
      @job.employer=current_employer
      @job.hyperlink.lstrip!
      if (!@job.hyperlink.empty?)&&(!(@job.hyperlink=~/http:\/\/.*|https:\/\/.*/))
        @job.hyperlink="http://"+@job.hyperlink
      end
      if @job.save
        ApplicationCalculationJob.perform_later(@job.id)
        redirect_to root_path, notice: 'Job was successfully uploaded.'
      else
        render :new
      end
    end
  end

  def destroy
    @job=Job.find(params[:id])
    File.delete("#{Rails.root}/public/#{@job.attachment}")
    File.delete("#{Rails.root}/#{@job.datafile}")
    @job.destroy
    redirect_to root_path, notice: 'The job has been deleted.'
  end
  private
    def set_job
      @job=Job.find(params[:id])
    end

    def job_params
      params.require(:job).permit(:position, :filename, :attachment, :description, :hyperlink, :job_type)
    end
end

app/views/jobs/_form.html.erb
<%= form_for @job do |f| %>
  <% if @job.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@resume.errors.count, "error") %> prevented this resume from being uploaded: </h2>
      <ul>
      <% @job.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label 'Position Name' %><br>
    <%= f.text_field :position, :placeholder=>"Position", :required=>'required' %>
  </div>
  <div class="field">
    <%= f.label 'Description (optional)' %><br>
    <%= f.text_field :description, :placeholder=>"Description" %>
  </div>
  <div class="field">
    <%= f.label 'Redirect Link (optional)' %><br>
    <%= f.text_field :hyperlink, :placeholder=>"http://example.com" %>
  </div>
  <div class="field">
    <%= f.label 'Upload Job'%><br>
    <%= f.file_field :attachment, :required=>'required' %>
  </div>
  <div class="field">
    <%= f.radio_button :job_type, 'Full-Time', :required=>'required' %>Full-Time
    <%= f.radio_button :job_type, 'Part-Time', :required=>'required'  %>Part-Time
    <%= f.radio_button :job_type, 'Internship', :required=>'required' %>Internship
  </div>   
  <div class="field">
    <%= f.submit 'Post Job', :class=>"button"%>
  </div>
<% end %>

app/views/jobs/all_index.html.erb
<div class="row align-center">
  <div class="column small-6 text-center">
    <h1> All Jobs </h1>
  </div>
</div>
<% if @jobs.size < 1 %>
Sorry, currently no jobs posted 
<% else %>
  <div class="row align-center">
    <div class="column small-12 text-center">
    <table class="hover">
      <tbody>
      <% @employers.each do |employer| %>
        <% employer.jobs.each do |job| %>
          <tr class="clickableRow" data-link="<%=job_path(job)%>">
           <td> <article>
             <h3 class="positionName"><%=job.position%></h3>
             <h4 class="employerName"><%=employer.companyName%></h4>
              <% if job.description %>
                <p><%=job.description%></p>
              <% end %>
              <h6><%=job.job_type%></h6>
            </article></td>
          </tr>
        <%end%>
      <%end%>
      </tbody>
    </table>
    </div>
  </div>
<% end %>

app/views/jobs/applicants.html.erb
<div class="row align-center">
  <div class="column small-10 text-center">
    <h2> Applicants for <%= @job.position %> </h2> 
    <% if @job.job_applications.size >= 1 %>
      <table class="table">
        <thread>
          <tr>
            <th style="text-align: center">Applicant</th>
          </tr>
        </thread>
        <tbody>
          <% @job.job_applications.each do |application| %>
            <tr>
              <td style="text-align: center"> <%=link_to application.user.name, resume_document_path(:id=>application.user.id,:job_id=>@job.id), :method=>:get %> </td>
            </tr>
          <% end %>
        <tbody>
      </table>
    <% else %>
      <h4> No one has applied for this position yet. </h4>
    <% end %>
    <h2>Possible Candidates</h2>
    <%if @tophash.size >=1%>
      <table class="table">
        <thread>
          <tr>
            <th style="text-align: center">Individual</th>
            <th style="text-align: center">Match</th>
          </tr>
        </thread>
        <tbody>
          <%@tophash.each do |candidate, value|%>
            <tr>
              <td style="text-align: center"><%=link_to value[0].name, resume_document_path(:id=>value[0].id, :job_id=>@job.id), :method=>:get%></td>
              <td style="text-align: center"> <%=value[1]%>%</td>
            </tr>
          <%end%>
        </tbody>
      </table>
    <%end%>

  </div>
</div>

app/views/jobs/index.html.erb
<h1> All Jobs </h1>
<% if @jobs.nil? %>
Sorry, currently no jobs posted 
<% else %>
  <% @employers.each do |employer| %>
    <% employer.jobs.each do |job| %>
      <%=job.position %> <br>
      <%=employer.companyName %>
      <br>
      <%=job.filename %>
      <br>
      <%= job.attachment %>
      <br>
---------------------------------------------------
    <br>
    <% end %>
    <br>
  <% end %>
<% end %>
<%= button_to 'Home', root_path, :class=>"button", :method => :get %>

app/views/jobs/my_index.html.erb
<div class="row align-center">
  <div class="column small-6 text-center">
    <h1> My Jobs </h1>
  </div>
</div>
<% if user_signed_in? %>
  <% if current_user.job_applications.size >= 1 %>
    <div class="row align-center">
    <div class="columns small-10 text-center">
    <table class="hover">
      <thread>
        <tr>
          <th style="text-align: center"> Position </th>
          <th style="text-align: center">Company</th>
          <th style="text-align: center"> Date Applied </th>
        </tr>
      </thread>
      <tbody>
      <% current_user.job_applications.each do |application| %>
        <tr class="clickableRow" data-link="<%=job_path(application.job)%>">
          <td>
            <%=application.job.position%>
          </td>
          <td>
            <%= application.job.employer.companyName%>
          </td>
          <td>
            <%=application.created_at.strftime("%m/%d/%Y")%>
          </td>
        </tr>
      <% end %>
      </tbody>
    </table>
    </div>
    </div>
  <% else %>
  <div class="row align-center">
    <div class="column small-6 text-center">
      You havent applied to any jobs
    </div>
  </div>
  <% end %>
<% else %>
  <% if current_employer.jobs.size >= 1 %>
  <div class="row align-center">
    <div class="columns small-10 text-center">
    <table class="hover">
      <thread>
        <tr>
          <th style="text-align: center"> Position </th>
          <th style="text-align: center"></th>
          <th style="text-align: center"> Date Posted </th>
        </tr>
      </thread>
      <tbody>
      <% current_employer.jobs.each_with_index do |job, index| %>
        <tr>
          <td>
            <%=link_to job.position, job_path(job), :method=>:get%> 
          </td>
          <td>
            <%= link_to "View Applicants", applicants_jobs_path(job), :method=>:get %>
          </td>
          <td>
            <%=job.created_at.strftime("%m/%d/%Y")%>
          </td>
        </tr>
      <% end %>
      </tbody>
    </table>
    </div>
    </div>
  <% else %>
  Post a Job Now!
  <%= button_to 'Post a Job', new_job_path, :class=>"button", :method=>:get %>
  <% end %>
<% end %>

app/views/jobs/new.html.erb
<br>
<div class="row align-center">
  <div class="column small-8 text-center">
    <h3> Upload A Job Posting </h3>
  </div>
</div>
<br>
<div class="row align-center">
  <div class="column small-4 text-center">
    <%= render 'form' %>
  </div>
</div> 

app/views/jobs/show.html.erb
<% if !@job %>
  <div class="row align-center">
    <div class="column small-6 text-center">
      An Error has occured.  Couldn't find job.
    </div>
  </div>
<% else %>
  <% if !@job_data %>
  <div class="row align-center">
    <div class="column small-6 text-center">
      Still analyzing document.  Try again in 10 seconds.
    </div>
  </div>
  <% else %>
    <div class="row align-center">
      <div class="column small-6 text-center">
        <h2><%= @job.position %></h2>
        <h3><i><%=@employer.companyName %></i></h3>
        <h5><%=@job.job_type%></h5>
      </div>
    </div>
    <ul class="tabs" data-tabs id="job-tabs">
      <li class="tabs-title is-active"><a href="#DocPanel">Document</a></li>
      <li class="tabs-title"><a href="#ReqPanel">Requirements</a></li>
    </ul>

     <div class="tabs-content" data-tabs-content="job-tabs">
       <div class="tabs-panel is-active" id="DocPanel">
         <% r=$client.post('viewdocument', {:mode=> 'document', :file=>open('public' + @job.attachment_url,'r')}) %>
         <div class="row align-center">
           <div class="column small-10 text-center">
             <%if @job.description%>
               <h4>Description</h4>
               <%=@job.description%>
               <br>
               <br>
             <%end%>
             <iframe srcdoc="<%=r.json%>" width="900" height="1000" style="border-style: solid; border-width: 10px; border-color:#425563;"></iframe>
           </div>
         </div>
       </div>

       <div class="tabs-panel" id="ReqPanel">
         <ul class="tabs" data-tabs id="job-requirements-tabs">
           <li class="tabs-title is-active"><a href="#AllReq">All</a></li>
           <li class="tabs-title"><a href="#ExperienceReq">Experience</a></li>
           <li class="tabs-title"><a href="#EducationReq">Education</a></li>
           <li class="tabs-title"><a href="#SkillReq">Skills</a></li>
         </ul>

         <div class="tabs-content" data-tabs-content="job-requirements-tabs">
           <div class="tabs-panel is-active" id="AllReq">
             <div class="row align-center">
               <div class="column small-6 text-center">

                 <h3>Experience</h3>
                 <%=@job_data["experience"]["start"]%>
                 <% if @job_data["experience"]["end"]<100%>
                   to <%=@job_data["experience"]["end"]%> years experience
                 <%else%>
                   or more years experience
                 <%end%>
                 <br>

                 <h3>Education</h3>
                 <%@job_data["education"].each do |edu|%>
                   <%= edu["level"]%> in <%=edu["degree"]%><br>
                 <%end%>
  
                 <h3>Skills</h3>
                 <%@job_data["skills"].each do |skill|%>
                     <%=skill%><br>
                 <%end%>
               </div>
             </div>
           </div>

           <div class="tabs-panel" id="ExperienceReq">
             <div class="row align-center">
               <div class="column small-6 text-center">
                 <h3>Experience</h3>
                 <%=@job_data["experience"]["start"]%>
                 <% if @job_data["experience"]["end"]<100%>
                   to <%=@job_data["experience"]["end"]%> years experience
                 <%else%>
                   or more years experience<br>
                 <%end%>
               </div>
             </div>
           </div>

           <div class="tabs-panel" id="EducationReq">
             <div class="row align-center">
               <div class="column small-6 text-center">
                 <h3>Education</h3>
                 <%@job_data["education"].each do |edu|%>
                   <%= edu["level"]%> in <%=edu["degree"]%><br>
                 <%end%>
               </div>
             </div>
           </div>

           <div class="tabs-panel" id="SkillReq">
             <div class="row align-center">
               <div class="column small-6 text-center">
                 <h3>Skills</h3>
                 <%@job_data["skills"].each do |skill|%>
                   <%=skill%><br>
                 <%end%>
               </div>
             </div>
           </div>

         </div>
       </div>
     </div>
  <%end%>
<%end%>

<div class="row align-center">
  <div class="column small-6 text-center">
  <% if @job.employer==current_employer %>
    <%= button_to "Delete This Posting", @job, :class=>"button", method: :delete, confirm: "Are you sure?" %>
  <% end %>
  </div>
</div>

app/views/jobs/top_job.html.erb
<div class="row align-center">
  <div class="column small-6 text-center">
    <h3> Your Top Job Matches </h3>
  </div>
</div>
<div class="row align-center">
  <div class="column small-12 text-center">
    <table class="table">
      <thread>
        <tr>
          <th style="text-align: center"> Position </th>
          <th style="text-align: center"> Company </th>
          <th style="text-align: center"> Match </th>
        </tr>
      </thread>
      <tbody>
      <% @tophash.each do |top| %>
        <tr>
          <td style="text-align: center">  <%=link_to top[1][1].position, top[1][1], :method=>:get %> </td>
          <td style="text-align: center"> <%= top[1][1].employer.companyName %> </td>
          <td style="text-align: center"> <%= (top[1][0])%>% </td>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>

<div class="row align-center">
  <div class="column small-12 text-center">
    <h3>Overall Category Match</h3>
  </div>
    <%if @industry_hash.size<3%>
      <%= column_chart (@industry_hash), max:100, colors:["#01A982"], label: "Overall Position Ranking", height: "35rem", width: "25rem"%>
    <%else%>
      <%=column_chart (@industry_hash), max:100, colors:["#01A982"], label: "Overall Position Ranking", height: "35rem", width: "50rem"%>
    <%end%>
</div>